version: '2'

services:

  app:
    build:
      context: .
      dockerfile: docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      DB_PORT: 5432
      DB_HOST: postgres
      DB_USER: app
      DB_PASS: app
      DB_NAME: app

  web:
    build:
      context: .
      dockerfile: docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  postgres:
    image: postgres:9.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

volumes:
  postgres-data:
